/*
 jTicketing is a highly configurable solution for the management of online booking, electronic ticket and box office.

 Copyright (C) 2010-2012 OpenPRJ s.r.l.
 All rights reserved

 Site: http://www.openprj.it
 Contact:  info@openprj.it
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.09.09 at 10:54:39 PM GMT+05:30
//


package it.openprj.jTicketing.backend.jaxb;

import java.util.ArrayList;
import java.util.HashMap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventCalendarResponceType", propOrder = {
	"eventCalendarPlaceId",
	"eventCalendarMonth",
	"eventCalendarYear",
	"eventCalendarDaysOfMonth"	
	

})


public class EventCalendarResponceType {
    
    @XmlElement(required = true)
	protected String eventCalendarPlaceId;
    @XmlElement(required = true)
    protected String eventCalendarMonth;
    @XmlElement(required = true)
    protected String eventCalendarYear;
    @XmlElement(required = true)
    protected ArrayList<TurnResponceType> eventCalendarDaysOfMonth = new ArrayList<TurnResponceType>();
	public String getEventCalendarPlaceId() {
		return eventCalendarPlaceId;
	}
	public void setEventCalendarPlaceId(String eventCalendarPlaceId) {
		this.eventCalendarPlaceId = eventCalendarPlaceId;
	}
	public String getEventCalendarMonth() {
		return eventCalendarMonth;
	}
	public void setEventCalendarMonth(String eventCalendarMonth) {
		this.eventCalendarMonth = eventCalendarMonth;
	}
	public String getEventCalendarYear() {
		return eventCalendarYear;
	}
	public void setEventCalendarYear(String eventCalendarYear) {
		this.eventCalendarYear = eventCalendarYear;
	}
	public ArrayList<TurnResponceType> getEventCalendarDaysOfMonth() {
		return eventCalendarDaysOfMonth;
	}
	public void setEventCalendarDaysOfMonth(
			ArrayList<TurnResponceType> eventCalendarDaysOfMonth) {
		this.eventCalendarDaysOfMonth = eventCalendarDaysOfMonth;
	}
	
	
	
}
