/*
 jTicketing is a highly configurable solution for the management of online booking, electronic ticket and box office.

 Copyright (C) 2010-2012 OpenPRJ s.r.l.
 All rights reserved

 Site: http://www.openprj.it
 Contact:  info@openprj.it
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.09.09 at 10:54:39 PM GMT+05:30
//


package it.openprj.jTicketing.backend.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for placeResponceType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="placeResponceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="placeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="placeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="placeImage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="placeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "placeResponceType", propOrder = {
    "placeId",
    "placeName",
    "placeImage",
    "placeDesc"
})
public class PlaceResponceType {

    @XmlElement(required = true)
    protected String placeId;
    @XmlElement(required = true)
    protected String placeName;
    @XmlElement(required = true)
    protected String placeImage;
    @XmlElement(required = true)
    protected String placeDesc;

    /**
     * Gets the value of the placeId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPlaceId() {
        return placeId;
    }

    /**
     * Sets the value of the placeId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPlaceId(String value) {
        this.placeId = value;
    }

    /**
     * Gets the value of the placeName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPlaceName() {
        return placeName;
    }

    /**
     * Sets the value of the placeName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPlaceName(String value) {
        this.placeName = value;
    }

    /**
     * Gets the value of the placeImage property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPlaceImage() {
        return placeImage;
    }

    /**
     * Sets the value of the placeImage property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPlaceImage(String value) {
        this.placeImage = value;
    }

    /**
     * Gets the value of the placeDesc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPlaceDesc() {
        return placeDesc;
    }

    /**
     * Sets the value of the placeDesc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPlaceDesc(String value) {
        this.placeDesc = value;
    }

}
