/*
 jTicketing is a highly configurable solution for the management of online booking, electronic ticket and box office.

 Copyright (C) 2010-2012 OpenPRJ s.r.l.
 All rights reserved

 Site: http://www.openprj.it
 Contact:  info@openprj.it
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.09.09 at 10:54:39 PM GMT+05:30
//


package it.openprj.jTicketing.backend.jaxb;

import java.math.BigDecimal;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for priceTicketResponceType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="priceTicketResponceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="priceUid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priceDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priceCondition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priceAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="priceStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="priceEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */


@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "priceTicketResponceType", propOrder = {
	"priceUid",
	"priceDesc",
	"priceCondition",
	"priceAmount",
	"priceStartDate",
	"priceEndDate"
})


public class PriceTicketResponceType {
    
    @XmlElement(required = true)
    protected String priceUid;
    @XmlElement(required = true)
    protected String priceDesc;
    @XmlElement(required = true)
    protected String priceCondition;
    @XmlElement(required = true)
    protected BigDecimal priceAmount;
    @XmlElement(required = true)
    protected Date priceStartDate;
    @XmlElement(required = true)
    protected Date priceEndDate;
	public String getPriceUid() {
		return priceUid;
	}
	public void setPriceUid(String priceUid) {
		this.priceUid = priceUid;
	}
	public String getPriceDesc() {
		return priceDesc;
	}
	public void setPriceDesc(String priceDesc) {
		this.priceDesc = priceDesc;
	}
	public String getPriceCondition() {
		return priceCondition;
	}
	public void setPriceCondition(String priceCondition) {
		this.priceCondition = priceCondition;
	}
	public BigDecimal getPriceAmount() {
		return priceAmount;
	}
	public void setPriceAmount(BigDecimal priceAmount) {
		this.priceAmount = priceAmount;
	}
	public Date getPriceStartDate() {
		return priceStartDate;
	}
	public void setPriceStartDate(Date priceStartDate) {
		this.priceStartDate = priceStartDate;
	}
	public Date getPriceEndDate() {
		return priceEndDate;
	}
	public void setPriceEndDate(Date priceEndDate) {
		this.priceEndDate = priceEndDate;
	}
    
	
   

}
