/*
 jTicketing is a highly configurable solution for the management of online booking, electronic ticket and box office.

 Copyright (C) 2010-2012 OpenPRJ s.r.l.
 All rights reserved

 Site: http://www.openprj.it
 Contact:  info@openprj.it
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.09.09 at 10:54:39 PM GMT+05:30
//


package it.openprj.jTicketing.backend.jaxb;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;




@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purchasedTicketResponceType", propOrder = {
    "purchasedTicketId",
    "purchasedTicketExpirationDate",
    "purchasedTicketDay",
    "purchasedTicketMonth",
    "purchasedTicketYear",
    "purchasedTicketTurn",
    "purchasedTicketVerificationCode",
    "purchasedTicket",
    "purchasedTicketTurnId",
    "purchasedTicketPrice",
    "purchasedTicketPlaceId",
    "purchasedTicketValidated",
    "purchasedTicketValidationDate",
    "purchasedTicketValidationOperator",
    "purchasedTicketBuyer"
})
public class PurchasedTicketResponceType {
    
    @XmlElement(required = true)
    private long purchasedTicketId;
    @XmlElement(required = true)
	private Date purchasedTicketExpirationDate;
    @XmlElement(required = true)
	private String purchasedTicketDay;
    @XmlElement(required = true)
	private String purchasedTicketMonth;
    @XmlElement(required = true)
	private String purchasedTicketYear;
    @XmlElement(required = true)
	private String purchasedTicketTurn;
    @XmlElement(required = true)
	private String purchasedTicketVerificationCode;
    @XmlElement(required = true)
	private TicketResponceType purchasedTicket;
    @XmlElement(required = true)
	private long purchasedTicketTurnId;
    @XmlElement(required = true)
	private PriceTicketResponceType purchasedTicketPrice;
    @XmlElement(required = true)
	private long purchasedTicketPlaceId;
    @XmlElement(required = true)
	private String purchasedTicketValidated;
    @XmlElement(required = true)
	private Date purchasedTicketValidationDate;
    @XmlElement(required = true)
	private UserResponceType purchasedTicketValidationOperator;
    @XmlElement(required = true)
	private UserResponceType purchasedTicketBuyer;
	public long getPurchasedTicketId() {
		return purchasedTicketId;
	}
	public void setPurchasedTicketId(long purchasedTicketId) {
		this.purchasedTicketId = purchasedTicketId;
	}
	public Date getPurchasedTicketExpirationDate() {
		return purchasedTicketExpirationDate;
	}
	public void setPurchasedTicketExpirationDate(Date purchasedTicketExpirationDate) {
		this.purchasedTicketExpirationDate = purchasedTicketExpirationDate;
	}
	public String getPurchasedTicketDay() {
		return purchasedTicketDay;
	}
	public void setPurchasedTicketDay(String purchasedTicketDay) {
		this.purchasedTicketDay = purchasedTicketDay;
	}
	public String getPurchasedTicketMonth() {
		return purchasedTicketMonth;
	}
	public void setPurchasedTicketMonth(String purchasedTicketMonth) {
		this.purchasedTicketMonth = purchasedTicketMonth;
	}
	public String getPurchasedTicketYear() {
		return purchasedTicketYear;
	}
	public void setPurchasedTicketYear(String purchasedTicketYear) {
		this.purchasedTicketYear = purchasedTicketYear;
	}
	public String getPurchasedTicketTurn() {
		return purchasedTicketTurn;
	}
	public void setPurchasedTicketTurn(String purchasedTicketTurn) {
		this.purchasedTicketTurn = purchasedTicketTurn;
	}
	public String getPurchasedTicketVerificationCode() {
		return purchasedTicketVerificationCode;
	}
	public void setPurchasedTicketVerificationCode(
			String purchasedTicketVerificationCode) {
		this.purchasedTicketVerificationCode = purchasedTicketVerificationCode;
	}
	public TicketResponceType getPurchasedTicket() {
		return purchasedTicket;
	}
	public void setPurchasedTicket(TicketResponceType purchasedTicket) {
		this.purchasedTicket = purchasedTicket;
	}
	public long getPurchasedTicketTurnId() {
		return purchasedTicketTurnId;
	}
	public void setPurchasedTicketTurnId(long purchasedTicketTurnId) {
		this.purchasedTicketTurnId = purchasedTicketTurnId;
	}
	public PriceTicketResponceType getPurchasedTicketPrice() {
		return purchasedTicketPrice;
	}
	public void setPurchasedTicketPrice(PriceTicketResponceType purchasedTicketPrice) {
		this.purchasedTicketPrice = purchasedTicketPrice;
	}
	public long getPurchasedTicketPlaceId() {
		return purchasedTicketPlaceId;
	}
	public void setPurchasedTicketPlaceId(long purchasedTicketPlaceId) {
		this.purchasedTicketPlaceId = purchasedTicketPlaceId;
	}
	public String getPurchasedTicketValidated() {
		return purchasedTicketValidated;
	}
	public void setPurchasedTicketValidated(String purchasedTicketValidated) {
		this.purchasedTicketValidated = purchasedTicketValidated;
	}
	public Date getPurchasedTicketValidationDate() {
		return purchasedTicketValidationDate;
	}
	public void setPurchasedTicketValidationDate(Date purchasedTicketValidationDate) {
		this.purchasedTicketValidationDate = purchasedTicketValidationDate;
	}
	public UserResponceType getPurchasedTicketValidationOperator() {
		return purchasedTicketValidationOperator;
	}
	public void setPurchasedTicketValidationOperator(
			UserResponceType purchasedTicketValidationOperator) {
		this.purchasedTicketValidationOperator = purchasedTicketValidationOperator;
	}
	public UserResponceType getPurchasedTicketBuyer() {
		return purchasedTicketBuyer;
	}
	public void setPurchasedTicketBuyer(UserResponceType purchasedTicketBuyer) {
		this.purchasedTicketBuyer = purchasedTicketBuyer;
	}	
    
    
   

}
