/*
 jTicketing is a highly configurable solution for the management of online booking, electronic ticket and box office.

 Copyright (C) 2010-2012 OpenPRJ s.r.l.
 All rights reserved

 Site: http://www.openprj.it
 Contact:  info@openprj.it
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.09.09 at 10:54:39 PM GMT+05:30
//


package it.openprj.jTicketing.backend.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "roleResponceType", propOrder = {		
	"roleId",
	"roleName",
	"roleUserId",
	"roleUsername"
	
})


public class RoleResponceType {   
    
    @XmlElement(required = true)    
    private long roleId;
    @XmlElement(required = true)    
	private String roleName = "";
    @XmlElement(required = true)    
	private long roleUserId;
    @XmlElement(required = true)   
    private String roleUsername = "";
	public long getRoleId() {
		return roleId;
	}
	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}
	public String getRoleName() {
		return roleName;
	}
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
	public long getRoleUserId() {
		return roleUserId;
	}
	public void setRoleUserId(long roleUserId) {
		this.roleUserId = roleUserId;
	}
	public String getRoleUsername() {
		return roleUsername;
	}
	public void setRoleUsername(String roleUsername) {
		this.roleUsername = roleUsername;
	}
 
	
}
