/*
 jTicketing is a highly configurable solution for the management of online booking, electronic ticket and box office.

 Copyright (C) 2010-2012 OpenPRJ s.r.l.
 All rights reserved

 Site: http://www.openprj.it
 Contact:  info@openprj.it
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.09.09 at 10:54:39 PM GMT+05:30
//


package it.openprj.jTicketing.backend.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "turnResponceType", propOrder = {		
	"turnTpEventHourId",
	"turnTaEventHourId",
	"turnHour",
	"turnStartHour",
	"turnQuantity",
	"turnRemainingQuantity",
	"turnEventCalendarId",
	"turnPlaceId",
	"turnTicketId",
	"turnDay",
	"turnPurchasedQuantity"
})


public class TurnResponceType {   
    
    @XmlElement(required = true)
    protected String turnTpEventHourId;
    @XmlElement(required = true)
	protected String turnTaEventHourId;
    @XmlElement(required = true)
	protected String turnHour;
    @XmlElement(required = true)
	protected String turnStartHour;
    @XmlElement(required = true)
	protected int turnQuantity;
    @XmlElement(required = true)
	protected int turnRemainingQuantity;
    @XmlElement(required = true)
	protected String turnEventCalendarId;
    @XmlElement(required = true)
	protected String turnPlaceId;
    @XmlElement(required = true)
	protected String turnTicketId;
    @XmlElement(required = true)
	protected String turnDay;
    @XmlElement(required = true)
	protected int turnPurchasedQuantity;
	public String getTurnTpEventHourId() {
		return turnTpEventHourId;
	}
	public void setTurnTpEventHourId(String turnTpEventHourId) {
		this.turnTpEventHourId = turnTpEventHourId;
	}
	public String getTurnTaEventHourId() {
		return turnTaEventHourId;
	}
	public void setTurnTaEventHourId(String turnTaEventHourId) {
		this.turnTaEventHourId = turnTaEventHourId;
	}
	public String getTurnHour() {
		return turnHour;
	}
	public void setTurnHour(String turnHour) {
		this.turnHour = turnHour;
	}
	public String getTurnStartHour() {
		return turnStartHour;
	}
	public void setTurnStartHour(String turnStartHour) {
		this.turnStartHour = turnStartHour;
	}
	public int getTurnQuantity() {
		return turnQuantity;
	}
	public void setTurnQuantity(int turnQuantity) {
		this.turnQuantity = turnQuantity;
	}
	public int getTurnRemainingQuantity() {
		return turnRemainingQuantity;
	}
	public void setTurnRemainingQuantity(int turnRemainingQuantity) {
		this.turnRemainingQuantity = turnRemainingQuantity;
	}
	public String getTurnEventCalendarId() {
		return turnEventCalendarId;
	}
	public void setTurnEventCalendarId(String turnEventCalendarId) {
		this.turnEventCalendarId = turnEventCalendarId;
	}
	public String getTurnPlaceId() {
		return turnPlaceId;
	}
	public void setTurnPlaceId(String turnPlaceId) {
		this.turnPlaceId = turnPlaceId;
	}
	public String getTurnTicketId() {
		return turnTicketId;
	}
	public void setTurnTicketId(String turnTicketId) {
		this.turnTicketId = turnTicketId;
	}
	public String getTurnDay() {
		return turnDay;
	}
	public void setTurnDay(String turnDay) {
		this.turnDay = turnDay;
	}
	public int getTurnPurchasedQuantity() {
		return turnPurchasedQuantity;
	}
	public void setTurnPurchasedQuantity(int turnPurchasedQuantity) {
		this.turnPurchasedQuantity = turnPurchasedQuantity;
	}
	
	

}
