/*
 jTicketing is a highly configurable solution for the management of online booking, electronic ticket and box office.

 Copyright (C) 2010-2012 OpenPRJ s.r.l.
 All rights reserved

 Site: http://www.openprj.it
 Contact:  info@openprj.it
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.09.09 at 10:54:39 PM GMT+05:30
//


package it.openprj.jTicketing.backend.jaxb;

import java.util.ArrayList;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userResponceType", propOrder = {		
	"userId",
	"userName",
	"userPass",
	"userFirstName",
	"userLastName",
	"userBirthdate",
	"userCF",
	"userEmail",
	"userActivationCode",
	"userEnabled",
	"userActivated",
	"userRole",
	"userBirthPlaceId",
	"userRoles"
		
})


public class UserResponceType {   
    
    @XmlElement(required = true)    
    private long userId;
    @XmlElement(required = true)    
	private String userName = "";
    @XmlElement(required = true)    
	private String userPass = "";
    @XmlElement(required = true)   
    private String userFirstName = "";
    @XmlElement(required = true)   
	private String userLastName = "";
    @XmlElement(required = true)   
    private Date userBirthdate;
    @XmlElement(required = true)   
    private String userCF;
    @XmlElement(required = true)   
	private String userEmail = "";
    @XmlElement(required = true)   
	private String userActivationCode = "";
    @XmlElement(required = true)   
	private boolean userEnabled = false;
    @XmlElement(required = true)   
	private boolean userActivated = false;
    @XmlElement(required = true)   
	private ArrayList<RoleResponceType> userRoles = new  ArrayList<RoleResponceType>();
    @XmlElement(required = true)   
	private String userRole;
    @XmlElement(required = true)   
	private long userBirthPlaceId;
	public long getUserId() {
		return userId;
	}
	public void setUserId(long userId) {
		this.userId = userId;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getUserPass() {
		return userPass;
	}
	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}
	public String getUserFirstName() {
		return userFirstName;
	}
	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}
	public String getUserLastName() {
		return userLastName;
	}
	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}
	public Date getUserBirthdate() {
		return userBirthdate;
	}
	public void setUserBirthdate(Date userBirthdate) {
		this.userBirthdate = userBirthdate;
	}
	public String getUserCF() {
		return userCF;
	}
	public void setUserCF(String userCF) {
		this.userCF = userCF;
	}
	public String getUserEmail() {
		return userEmail;
	}
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}
	public String getUserActivationCode() {
		return userActivationCode;
	}
	public void setUserActivationCode(String userActivationCode) {
		this.userActivationCode = userActivationCode;
	}
	public boolean isUserEnabled() {
		return userEnabled;
	}
	public void setUserEnabled(boolean userEnabled) {
		this.userEnabled = userEnabled;
	}
	public boolean isUserActivated() {
		return userActivated;
	}
	public void setUserActivated(boolean userActivated) {
		this.userActivated = userActivated;
	}
	public ArrayList<RoleResponceType> getUserRoles() {
		return userRoles;
	}
	public void setUserRoles(ArrayList<RoleResponceType> userRoles) {
		this.userRoles = userRoles;
	}
	public String getUserRole() {
		return userRole;
	}
	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}
	public long getUserBirthPlaceId() {
		return userBirthPlaceId;
	}
	public void setUserBirthPlaceId(long userBirthPlaceId) {
		this.userBirthPlaceId = userBirthPlaceId;
	}   
	
	
    

	
	

}
